//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 10:21:16 AM IST 
//


package pac1.Bean.nfLayouts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}interfaceSimulationCompId"/>
 *         &lt;element ref="{}serviceName"/>
 *         &lt;element ref="{}interfaceId"/>
 *         &lt;element ref="{}serviceMode"/>
 *         &lt;element ref="{}serviceType"/>
 *         &lt;element ref="{}interfaceSimulationProperties"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interfaceSimulationCompId",
    "serviceName",
    "interfaceId",
    "serviceMode",
    "serviceType",
    "interfaceSimulationProperties"
})
@XmlRootElement(name = "interfaceSimulationComponent")
public class InterfaceSimulationComponent implements java.io.Serializable{

    @XmlElement(required = true)
    protected String interfaceSimulationCompId;
    @XmlElement(required = true)
    protected String serviceName;
    @XmlElement(required = true)
    protected String interfaceId;
    @XmlElement(required = true)
    protected String serviceMode;
    @XmlElement(required = true)
    protected String serviceType;
    @XmlElement(required = true)
    protected InterfaceSimulationProperties interfaceSimulationProperties;

    /**
     * Gets the value of the interfaceSimulationCompId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceSimulationCompId() {
        return interfaceSimulationCompId;
    }

    /**
     * Sets the value of the interfaceSimulationCompId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceSimulationCompId(String value) {
        this.interfaceSimulationCompId = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the interfaceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceId() {
        return interfaceId;
    }

    /**
     * Sets the value of the interfaceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceId(String value) {
        this.interfaceId = value;
    }

    /**
     * Gets the value of the serviceMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceMode() {
        return serviceMode;
    }

    /**
     * Sets the value of the serviceMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceMode(String value) {
        this.serviceMode = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the interfaceSimulationProperties property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceSimulationProperties }
     *     
     */
    public InterfaceSimulationProperties getInterfaceSimulationProperties() {
        return interfaceSimulationProperties;
    }

    /**
     * Sets the value of the interfaceSimulationProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceSimulationProperties }
     *     
     */
    public void setInterfaceSimulationProperties(InterfaceSimulationProperties value) {
        this.interfaceSimulationProperties = value;
    }

}
