//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 10:21:16 AM IST 
//


package pac1.Bean.nfLayouts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}interfaceCompId"/>
 *         &lt;element ref="{}interfaceCompName"/>
 *         &lt;element ref="{}begCompId"/>
 *         &lt;element ref="{}endCompId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interfaceCompId",
    "interfaceCompName",
    "begCompId",
    "endCompId"
})
@XmlRootElement(name = "interfaceComponent")
public class InterfaceComponent implements java.io.Serializable{

    @XmlElement(required = true)
    protected String interfaceCompId;
    @XmlElement(required = true)
    protected String interfaceCompName;
    @XmlElement(required = true)
    protected String begCompId;
    @XmlElement(required = true)
    protected String endCompId;

    /**
     * Gets the value of the interfaceCompId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceCompId() {
        return interfaceCompId;
    }

    /**
     * Sets the value of the interfaceCompId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceCompId(String value) {
        this.interfaceCompId = value;
    }

    /**
     * Gets the value of the interfaceCompName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceCompName() {
        return interfaceCompName;
    }

    /**
     * Sets the value of the interfaceCompName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceCompName(String value) {
        this.interfaceCompName = value;
    }

    /**
     * Gets the value of the begCompId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBegCompId() {
        return begCompId;
    }

    /**
     * Sets the value of the begCompId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBegCompId(String value) {
        this.begCompId = value;
    }

    /**
     * Gets the value of the endCompId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndCompId() {
        return endCompId;
    }

    /**
     * Sets the value of the endCompId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndCompId(String value) {
        this.endCompId = value;
    }

}
