//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 10:21:16 AM IST 
//


package pac1.Bean.nfLayouts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}layoutName"/>
 *         &lt;element ref="{}layoutDescription"/>
 *         &lt;element ref="{}canvas_width"/>
 *         &lt;element ref="{}canvas_height"/>
 *         &lt;element ref="{}layoutComponent" maxOccurs="unbounded"/>
 *         &lt;element ref="{}interfaceComponent" maxOccurs="unbounded"/>
 *         &lt;element ref="{}interfaceSimulationComponent" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "layoutName",
    "layoutDescription",
    "canvasWidth",
    "canvasHeight",
    "layoutComponent",
    "interfaceComponent",
    "interfaceSimulationComponent"
})
@XmlRootElement(name = "Layouts")
public class Layouts implements java.io.Serializable{

    @XmlElement(required = true)
    protected String layoutName;
    @XmlElement(required = true)
    protected String layoutDescription;
    @XmlElement(name = "canvas_width", required = true)
    protected String canvasWidth;
    @XmlElement(name = "canvas_height", required = true)
    protected String canvasHeight;
    @XmlElement(required = true)
    protected List<LayoutComponent> layoutComponent;
    @XmlElement(required = true)
    protected List<InterfaceComponent> interfaceComponent;
    @XmlElement(required = true)
    protected List<InterfaceSimulationComponent> interfaceSimulationComponent;

    /**
     * Gets the value of the layoutName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutName() {
        return layoutName;
    }

    /**
     * Sets the value of the layoutName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutName(String value) {
        this.layoutName = value;
    }

    /**
     * Gets the value of the layoutDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutDescription() {
        return layoutDescription;
    }

    /**
     * Sets the value of the layoutDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutDescription(String value) {
        this.layoutDescription = value;
    }

    /**
     * Gets the value of the canvasWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvasWidth() {
        return canvasWidth;
    }

    /**
     * Sets the value of the canvasWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvasWidth(String value) {
        this.canvasWidth = value;
    }

    /**
     * Gets the value of the canvasHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvasHeight() {
        return canvasHeight;
    }

    /**
     * Sets the value of the canvasHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvasHeight(String value) {
        this.canvasHeight = value;
    }

    /**
     * Gets the value of the layoutComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layoutComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayoutComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LayoutComponent }
     * 
     * 
     */
    public List<LayoutComponent> getLayoutComponent() {
        if (layoutComponent == null) {
            layoutComponent = new ArrayList<LayoutComponent>();
        }
        return this.layoutComponent;
    }

    /**
     * Gets the value of the interfaceComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interfaceComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterfaceComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterfaceComponent }
     * 
     * 
     */
    public List<InterfaceComponent> getInterfaceComponent() {
        if (interfaceComponent == null) {
            interfaceComponent = new ArrayList<InterfaceComponent>();
        }
        return this.interfaceComponent;
    }

    /**
     * Gets the value of the interfaceSimulationComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interfaceSimulationComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterfaceSimulationComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterfaceSimulationComponent }
     * 
     * 
     */
    public List<InterfaceSimulationComponent> getInterfaceSimulationComponent() {
        if (interfaceSimulationComponent == null) {
            interfaceSimulationComponent = new ArrayList<InterfaceSimulationComponent>();
        }
        return this.interfaceSimulationComponent;
    }

}
