//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 10:21:16 AM IST 
//


package pac1.Bean.nfLayouts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}xAxisLayoutProp"/>
 *         &lt;element ref="{}yAxisLayoutProp"/>
 *         &lt;element ref="{}widthLayoutProp"/>
 *         &lt;element ref="{}heightLayoutProp"/>
 *         &lt;element ref="{}bgColorLayoutProp"/>
 *         &lt;element ref="{}fgColorLayoutProp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xAxisLayoutProp",
    "yAxisLayoutProp",
    "widthLayoutProp",
    "heightLayoutProp",
    "bgColorLayoutProp",
    "fgColorLayoutProp"
})
@XmlRootElement(name = "layoutProperties")
public class LayoutProperties implements java.io.Serializable{

    @XmlElement(required = true)
    protected String xAxisLayoutProp;
    @XmlElement(required = true)
    protected String yAxisLayoutProp;
    @XmlElement(required = true)
    protected String widthLayoutProp;
    @XmlElement(required = true)
    protected String heightLayoutProp;
    @XmlElement(required = true)
    protected String bgColorLayoutProp;
    @XmlElement(required = true)
    protected String fgColorLayoutProp;

    /**
     * Gets the value of the xAxisLayoutProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXAxisLayoutProp() {
        return xAxisLayoutProp;
    }

    /**
     * Sets the value of the xAxisLayoutProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXAxisLayoutProp(String value) {
        this.xAxisLayoutProp = value;
    }

    /**
     * Gets the value of the yAxisLayoutProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYAxisLayoutProp() {
        return yAxisLayoutProp;
    }

    /**
     * Sets the value of the yAxisLayoutProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYAxisLayoutProp(String value) {
        this.yAxisLayoutProp = value;
    }

    /**
     * Gets the value of the widthLayoutProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthLayoutProp() {
        return widthLayoutProp;
    }

    /**
     * Sets the value of the widthLayoutProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthLayoutProp(String value) {
        this.widthLayoutProp = value;
    }

    /**
     * Gets the value of the heightLayoutProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeightLayoutProp() {
        return heightLayoutProp;
    }

    /**
     * Sets the value of the heightLayoutProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeightLayoutProp(String value) {
        this.heightLayoutProp = value;
    }

    /**
     * Gets the value of the bgColorLayoutProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgColorLayoutProp() {
        return bgColorLayoutProp;
    }

    /**
     * Sets the value of the bgColorLayoutProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgColorLayoutProp(String value) {
        this.bgColorLayoutProp = value;
    }

    /**
     * Gets the value of the fgColorLayoutProp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFgColorLayoutProp() {
        return fgColorLayoutProp;
    }

    /**
     * Sets the value of the fgColorLayoutProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFgColorLayoutProp(String value) {
        this.fgColorLayoutProp = value;
    }

}
