//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 10:21:16 AM IST 
//


package pac1.Bean.nfLayouts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}layoutCompId"/>
 *         &lt;element ref="{}layoutCompName"/>
 *         &lt;element ref="{}layoutProperties"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "layoutCompId",
    "layoutCompName",
    "layoutProperties"
})
@XmlRootElement(name = "layoutComponent")
public class LayoutComponent implements java.io.Serializable{

    @XmlElement(required = true)
    protected String layoutCompId;
    @XmlElement(required = true)
    protected String layoutCompName;
    @XmlElement(required = true)
    protected LayoutProperties layoutProperties;

    /**
     * Gets the value of the layoutCompId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutCompId() {
        return layoutCompId;
    }

    /**
     * Sets the value of the layoutCompId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutCompId(String value) {
        this.layoutCompId = value;
    }

    /**
     * Gets the value of the layoutCompName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutCompName() {
        return layoutCompName;
    }

    /**
     * Sets the value of the layoutCompName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutCompName(String value) {
        this.layoutCompName = value;
    }

    /**
     * Gets the value of the layoutProperties property.
     * 
     * @return
     *     possible object is
     *     {@link LayoutProperties }
     *     
     */
    public LayoutProperties getLayoutProperties() {
        return layoutProperties;
    }

    /**
     * Sets the value of the layoutProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayoutProperties }
     *     
     */
    public void setLayoutProperties(LayoutProperties value) {
        this.layoutProperties = value;
    }

}
