//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.08.08 at 06:26:00 PM IST
//


package pac1.Bean.VUserTrace;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory implements Serializable{

    private final static QName _StartSessionTime_QNAME = new QName("", "StartSessionTime");
    private final static QName _PageName_QNAME = new QName("", "PageName");
    private final static QName _Value_QNAME = new QName("", "Value");
    private final static QName _SessionID_QNAME = new QName("", "SessionID");
    private final static QName _HTTPStatusCode_QNAME = new QName("", "HTTPStatusCode");
    private final static QName _PageStatus_QNAME = new QName("", "PageStatus");
    private final static QName _ParameterType_QNAME = new QName("", "ParameterType");
    private final static QName _ResponseTime_QNAME = new QName("", "ResponseTime");
    private final static QName _Response_QNAME = new QName("", "Response");
    private final static QName _PageThinkTime_QNAME = new QName("", "PageThinkTime");
    private final static QName _Request_QNAME = new QName("", "Request");
    private final static QName _ScriptName_QNAME = new QName("", "ScriptName");
    private final static QName _SessionStatus_QNAME = new QName("", "SessionStatus");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _Status_QNAME = new QName("", "Status");
    private final static QName _Detail_QNAME = new QName("", "Detail");
    private final static QName _ResponseBody_QNAME = new QName("", "ResponseBody");
    private final static QName _ID_QNAME = new QName("", "ID");
    private final static QName _ORD_QNAME = new QName("", "ORD");
    private final static QName _StartTime_QNAME = new QName("", "StartTime");
    private final static QName _SessionTime_QNAME = new QName("", "SessionTime");
    private final static QName _Protocol_QNAME = new QName("", "Protocol");
    private final static QName _RequestURL_QNAME = new QName("", "RequestURL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StartSession }
     *
     */
    public StartSession createStartSession() {
        return new StartSession();
    }

    /**
     * Create an instance of {@link Parameter }
     *
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Pages }
     *
     */
    public Pages createPages() {
        return new Pages();
    }

    /**
     * Create an instance of {@link UserTrace }
     *
     */
    public UserTrace createUserTrace() {
        return new UserTrace();
    }

    /**
     * Create an instance of {@link Validations }
     *
     */
    public Validations createValidations() {
        return new Validations();
    }

    /**
     * Create an instance of {@link EndSession }
     *
     */
    public EndSession createEndSession() {
        return new EndSession();
    }

    /**
     * Create an instance of {@link Checkpoint }
     *
     */
    public Checkpoint createCheckpoint() {
        return new Checkpoint();
    }

    /**
     * Create an instance of {@link Parameterization }
     *
     */
    public Parameterization createParameterization() {
        return new Parameterization();
    }

    /**
     * Create an instance of {@link SearchParameter }
     *
     */
    public SearchParameter createSearchParameter() {
        return new SearchParameter();
    }

    /**
     * Create an instance of {@link Page }
     *
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link SearchParameters }
     *
     */
    public SearchParameters createSearchParameters() {
        return new SearchParameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "StartSessionTime")
    public JAXBElement<String> createStartSessionTime(String value) {
        return new JAXBElement<String>(_StartSessionTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PageName")
    public JAXBElement<String> createPageName(String value) {
        return new JAXBElement<String>(_PageName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "SessionID")
    public JAXBElement<String> createSessionID(String value) {
        return new JAXBElement<String>(_SessionID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "HTTPStatusCode")
    public JAXBElement<String> createHTTPStatusCode(String value) {
        return new JAXBElement<String>(_HTTPStatusCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PageStatus")
    public JAXBElement<String> createPageStatus(String value) {
        return new JAXBElement<String>(_PageStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ParameterType")
    public JAXBElement<String> createParameterType(String value) {
        return new JAXBElement<String>(_ParameterType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ResponseTime")
    public JAXBElement<String> createResponseTime(String value) {
        return new JAXBElement<String>(_ResponseTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Response")
    public JAXBElement<String> createResponse(String value) {
        return new JAXBElement<String>(_Response_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PageThinkTime")
    public JAXBElement<String> createPageThinkTime(String value) {
        return new JAXBElement<String>(_PageThinkTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Request")
    public JAXBElement<String> createRequest(String value) {
        return new JAXBElement<String>(_Request_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ScriptName")
    public JAXBElement<String> createScriptName(String value) {
        return new JAXBElement<String>(_ScriptName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "SessionStatus")
    public JAXBElement<String> createSessionStatus(String value) {
        return new JAXBElement<String>(_SessionStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Detail")
    public JAXBElement<String> createDetail(String value) {
        return new JAXBElement<String>(_Detail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ResponseBody")
    public JAXBElement<String> createResponseBody(String value) {
        return new JAXBElement<String>(_ResponseBody_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ID")
    public JAXBElement<String> createID(String value) {
        return new JAXBElement<String>(_ID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ORD")
    public JAXBElement<String> createORD(String value) {
        return new JAXBElement<String>(_ORD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "StartTime")
    public JAXBElement<String> createStartTime(String value) {
        return new JAXBElement<String>(_StartTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "SessionTime")
    public JAXBElement<String> createSessionTime(String value) {
        return new JAXBElement<String>(_SessionTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Protocol")
    public JAXBElement<String> createProtocol(String value) {
        return new JAXBElement<String>(_Protocol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "RequestURL")
    public JAXBElement<String> createRequestURL(String value) {
        return new JAXBElement<String>(_RequestURL_QNAME, String.class, null, value);
    }

}
