//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.21 at 02:18:40 PM IST
//


package pac1.Bean.VUserTrace;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PageName"/>
 *         &lt;element ref="{}StartTime"/>
 *         &lt;element ref="{}Protocol"/>
 *         &lt;element ref="{}ResponseTime"/>
 *         &lt;element ref="{}HTTPStatusCode"/>
 *         &lt;element ref="{}PageStatus"/>
 *         &lt;element ref="{}PageThinkTime"/>
 *         &lt;element ref="{}RequestURL"/>
 *         &lt;element ref="{}InCache"/>
 *         &lt;element ref="{}SearchParameters"/>
 *         &lt;element ref="{}Parameterization"/>
 *         &lt;element ref="{}Validations"/>
 *         &lt;element ref="{}Request"/>
 *         &lt;element ref="{}Response"/>
 *         &lt;element ref="{}ResponseBody"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pageName",
    "startTime",
    "protocol",
    "responseTime",
    "httpStatusCode",
    "pageStatus",
    "pageThinkTime",
    "requestURL",
    "inCache",
    "searchParameters",
    "parameterization",
    "validations",
    "request",
    "response",
    "responseBody"
})
@XmlRootElement(name = "Page")
public class Page implements Serializable{

    @XmlElement(name = "PageName", required = true)
    protected String pageName;
    @XmlElement(name = "StartTime", required = true)
    protected String startTime;
    @XmlElement(name = "Protocol", required = true)
    protected String protocol;
    @XmlElement(name = "ResponseTime", required = true)
    protected String responseTime;
    @XmlElement(name = "HTTPStatusCode", required = true)
    protected String httpStatusCode;
    @XmlElement(name = "PageStatus", required = true)
    protected String pageStatus;
    @XmlElement(name = "PageThinkTime", required = true)
    protected String pageThinkTime;
    @XmlElement(name = "RequestURL", required = true)
    protected String requestURL;
    @XmlElement(name = "InCache", required = true)
    protected String inCache;
    @XmlElement(name = "SearchParameters", required = true)
    protected SearchParameters searchParameters;
    @XmlElement(name = "Parameterization", required = true)
    protected Parameterization parameterization;
    @XmlElement(name = "Validations", required = true)
    protected Validations validations;
    @XmlElement(name = "Request", required = true)
    protected String request;
    @XmlElement(name = "Response", required = true)
    protected String response;
    @XmlElement(name = "ResponseBody", required = true)
    protected String responseBody;

    /**
     * Gets the value of the pageName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * Sets the value of the pageName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPageName(String value) {
        this.pageName = value;
    }

    /**
     * Gets the value of the startTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the protocol property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the responseTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * Sets the value of the responseTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResponseTime(String value) {
        this.responseTime = value;
    }

    /**
     * Gets the value of the httpStatusCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHTTPStatusCode() {
        return httpStatusCode;
    }

    /**
     * Sets the value of the httpStatusCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHTTPStatusCode(String value) {
        this.httpStatusCode = value;
    }

    /**
     * Gets the value of the pageStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPageStatus() {
        return pageStatus;
    }

    /**
     * Sets the value of the pageStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPageStatus(String value) {
        this.pageStatus = value;
    }

    /**
     * Gets the value of the pageThinkTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPageThinkTime() {
        return pageThinkTime;
    }

    /**
     * Sets the value of the pageThinkTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPageThinkTime(String value) {
        this.pageThinkTime = value;
    }

    /**
     * Gets the value of the requestURL property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRequestURL() {
        return requestURL;
    }

    /**
     * Sets the value of the requestURL property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRequestURL(String value) {
        this.requestURL = value;
    }

    /**
     * Gets the value of the inCache property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInCache() {
        return inCache;
    }

    /**
     * Sets the value of the inCache property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInCache(String value) {
        this.inCache = value;
    }

    /**
     * Gets the value of the searchParameters property.
     *
     * @return
     *     possible object is
     *     {@link SearchParameters }
     *
     */
    public SearchParameters getSearchParameters() {
        return searchParameters;
    }

    /**
     * Sets the value of the searchParameters property.
     *
     * @param value
     *     allowed object is
     *     {@link SearchParameters }
     *
     */
    public void setSearchParameters(SearchParameters value) {
        this.searchParameters = value;
    }

    /**
     * Gets the value of the parameterization property.
     *
     * @return
     *     possible object is
     *     {@link Parameterization }
     *
     */
    public Parameterization getParameterization() {
        return parameterization;
    }

    /**
     * Sets the value of the parameterization property.
     *
     * @param value
     *     allowed object is
     *     {@link Parameterization }
     *
     */
    public void setParameterization(Parameterization value) {
        this.parameterization = value;
    }

    /**
     * Gets the value of the validations property.
     *
     * @return
     *     possible object is
     *     {@link Validations }
     *
     */
    public Validations getValidations() {
        return validations;
    }

    /**
     * Sets the value of the validations property.
     *
     * @param value
     *     allowed object is
     *     {@link Validations }
     *
     */
    public void setValidations(Validations value) {
        this.validations = value;
    }

    /**
     * Gets the value of the request property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRequest(String value) {
        this.request = value;
    }

    /**
     * Gets the value of the response property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResponse(String value) {
        this.response = value;
    }

    /**
     * Gets the value of the responseBody property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResponseBody() {
        return responseBody;
    }

    /**
     * Sets the value of the responseBody property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResponseBody(String value) {
        this.responseBody = value;
    }

}
